title: Justin Ma
description: >
After working mainly in front end design I've made the switch into a more
technical role that is now finding the balance between Design and Big Data in order to bringing the conceptual down to reality.
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "#"
linkedin_username: "justinmadata"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "#"
feed_icon: rss
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
